name: GitHub CI

on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  windowsBuildLLVM:
    name: Windows Build
    runs-on: windows-2019
    env:
      BUILD_PROJECT: llvm
      BUILD_MASTER: false
      LLVM_VERSION: 15.0.4
      MSVC: msvc16

    strategy:
      fail-fast: false
      matrix:
        CRT:
          - msvcrt
        # - libcmt

        TARGET_CPU:
          # - amd64
          - amd64

        CONFIGURATION:
          # - Debug
          - Release

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install
        shell: cmd
        run: |
          call %GITHUB_WORKSPACE%\set-env.bat ${{env.MSVC}} ${{matrix.CRT}} ${{matrix.TARGET_CPU}} ${{matrix.CONFIGURATION}}
          call %GITHUB_WORKSPACE%\install.bat

      - name: Build
        id: BUILD
        shell: cmd
        run: |
          call %GITHUB_WORKSPACE%\set-env.bat ${{env.MSVC}} ${{matrix.CRT}} ${{matrix.TARGET_CPU}} ${{matrix.CONFIGURATION}}
          call %GITHUB_WORKSPACE%\build.bat
          echo DEPLOY_FILE=%DEPLOY_FILE% >> %GITHUB_OUTPUT%

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          tag_name: ${{ github.ref_name }}
          draft: true
          prerelease: false
          files: ${{steps.BUILD.outputs.DEPLOY_FILE}}

  windowsBuildClang:
    needs: windowsBuildLLVM
    continue-on-error: true
    name: Windows Build
    runs-on: windows-2019
    env:
      BUILD_PROJECT: clang
      BUILD_MASTER: false
      LLVM_VERSION: 15.0.4
      MSVC: msvc16

    strategy:
      fail-fast: false
      matrix:
        CRT:
          - msvcrt
        # - libcmt

        TARGET_CPU:
          # - amd64
          - amd64

        CONFIGURATION:
          # - Debug
          - Release

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install
        shell: cmd
        run: |
          call %GITHUB_WORKSPACE%\set-env.bat ${{env.MSVC}} ${{matrix.CRT}} ${{matrix.TARGET_CPU}} ${{matrix.CONFIGURATION}}
          call %GITHUB_WORKSPACE%\install.bat

      - name: Build
        id: BUILD
        shell: cmd
        run: |
          call %GITHUB_WORKSPACE%\set-env.bat ${{env.MSVC}} ${{matrix.CRT}} ${{matrix.TARGET_CPU}} ${{matrix.CONFIGURATION}}
          call %GITHUB_WORKSPACE%\build.bat
          echo DEPLOY_FILE=%DEPLOY_FILE% >> %GITHUB_OUTPUT%

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          tag_name: ${{ github.ref_name }}
          draft: true
          prerelease: false
          files: ${{steps.BUILD.outputs.DEPLOY_FILE}}

